name: GitHub Classroom Workflow
on: [push, pull_request]
permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install libssl1.1
        run: |
          sudo add-apt-repository ppa:rael-gc/rvm -y
          sudo apt update
          sudo apt install libssl1.1 -y
      - uses: education/autograding@v1